{% set name = "napari-buds" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-buds-{{ version }}.tar.gz
  sha256: 8e2f2028447c4544540ad81d90b9f4db840eae7ca2ef124f4ec29f4d06f2a2c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - napari
    - numpy
    - python >={{ python_min }}
    - qtpy
    - pandas
    - magic-class
    - scipy
    - scikit-learn
    - scikit-image
    - matplotlib-base
    - joblib
    - imageio-ffmpeg
    - stackview
    - jupyterlab

test:
  imports:
    - napari_buds
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SanderSMFISH/napari-buds
  summary: Random-forest automated bud annotation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
